# Generated by Django 6.0.8 on 2026-08-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(default='vi', max_length=10),
        ),
    ]
